# Generated by Django 4.2.6 on 2023-11-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple', models.CharField(max_length=100)),
                ('lenovo', models.CharField(max_length=100)),
                ('asus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='aplikasi_utama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toko', models.CharField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.kategori')),
            ],
        ),
    ]
